.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. stratis_qt test_stratis_qt
clean: FORCE
	$(MAKE) -C .. stratis_qt_clean test_stratis_qt_clean
check: FORCE
	$(MAKE) -C .. test_stratis_qt_check
stratis-qt stratis-qt.exe: FORCE
	 $(MAKE) -C .. stratis_qt
