.TH STRATIS-CLI "1" "February 2016" "stratis-cli 0.12"
.SH NAME
stratis-cli \- a remote procedure call client for Stratis Core. 
.SH SYNOPSIS
stratis-cli [options] <command> [params] \- Send command to Stratis Core. 
.TP
stratis-cli [options] help \- Asks Stratis Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the stratis-cli program. stratis-cli is an RPC client used to send commands to Stratis Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBstratisd\fP, \fBstratis.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
